from typing import Protocol

from users.core.tokens.domain.token import RefreshToken, RefreshTokenId
from users.core.tokens.domain.token_user import TokenUser

from ..shared import UserId


class TokenRepository(Protocol):
    async def find_by_token(self, refresh_token: str) -> RefreshToken | None: ...
    async def find_user_by_refresh_token_id(
        self, refresh_token_id: RefreshTokenId
    ) -> TokenUser | None: ...
    async def find_user_by_refresh_token(
        self, refresh_token: str
    ) -> TokenUser | None: ...
    async def find_user_by_id(self, id: UserId) -> TokenUser | None: ...
    async def find_user_by_email(self, email: str) -> TokenUser | None: ...
    async def save_refresh_token(self, refresh_token: RefreshToken) -> None: ...
    async def remove_refresh_token(
        self, user_id: UserId, refresh_token: str
    ) -> None: ...
