version: "3.9"
name: user-service
services:
  user_db:
    image: postgres:17-alpine
    container_name: user-db
    ports:
      - "54321:5432"
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=users
    volumes:
      - ./data:/var/lib/postgresql/data
    networks:
      - internal
 
  user_service:
    container_name: user-service
    build:
      context: .
    env_file: .env
    ports:
      - "8002:8000"
    networks:
      - internal

networks:
  internal:
    name: project-internal
    external: true
