from typing import Protocol

from ..shared.id import RoleId
from .domain import Permission, Role


class RoleRepository(Protocol):
    async def find_by_id(self, role_id: RoleId) -> Role | None: ...
    async def save(self, role: Role) -> None: ...
    async def delete(self, role: Role) -> None: ...

    async def find_permission(self, namespace: str, name: str) -> Permission | None: ...
    async def ensure_permission_exists(self, permission: Permission) -> Permission: ...
    async def ensure_permission_deleted(self, permission: Permission) -> None: ...
    async def any_role_uses_permission(self, permission: Permission) -> bool: ...
