"""split permission table

Revision ID: 6de16db1b738
Revises: 1fb3d8fc2f92
Create Date: 2025-02-12 14:35:52.349041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6de16db1b738'
down_revision: Union[str, None] = '1fb3d8fc2f92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_permissions',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('permission_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.drop_constraint('permissions_role_id_fkey', 'permissions', type_='foreignkey')
    op.drop_column('permissions', 'role_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('role_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_foreign_key('permissions_role_id_fkey', 'permissions', 'roles', ['role_id'], ['id'])
    op.drop_table('role_permissions')
    # ### end Alembic commands ###
