"""add soft delete capability

Revision ID: 1fb3d8fc2f92
Revises: ccd552b49a8b
Create Date: 2025-02-08 20:54:47.469969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fb3d8fc2f92'
down_revision: Union[str, None] = 'ccd552b49a8b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('permissions', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('roles', 'deleted_at')
    op.drop_column('refresh_tokens', 'deleted_at')
    op.drop_column('profiles', 'deleted_at')
    op.drop_column('permissions', 'deleted_at')
    # ### end Alembic commands ###
